# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: Emulator
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
        displayName: "Run Azure Cosmos DB Emulator container"
        inputs:
          defaultPartitionCount: 25
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        displayName: "Install Node.js"

      - script: npm run install-client-cosmos
        displayName: "npm install-client-cosmos"

      - script: npm run build-client-cosmos
        displayName: "npm run build-client-cosmos"

      - bash: ACCOUNT_HOST=$COSMOSDBEMULATOR_ENDPOINT NODE_TLS_REJECT_UNAUTHORIZED="0" npm run test-client-cosmos
        failOnStderr: true
        displayName: "npm test"
        env:
          MOCHA_TIMEOUT: 100000
  # - job: NightlyEmulator
  #   pool:
  #     vmImage: vs2017-win2016
  #   steps:
  #     - task: azure-cosmosdb.emulator-internal-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
  #       displayName: "Run Azure Cosmos DB Emulator container"
  #       inputs:
  #         username: "$(cosmosdb.azurecr.io.Username)"
  #         password: "$(cosmosdb.azurecr.io.Password)"
  #         defaultPartitionCount: 25
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: "10.x"
  #       displayName: "Install Node.js"

  #     - script: npm run install-client-cosmos
  #       displayName: "npm install-client-cosmos"

  #     - script: npm run build-client-cosmos
  #       displayName: "npm run build-client-cosmos"

  #     - bash: ACCOUNT_HOST=$COSMOSDBEMULATOR_ENDPOINT NODE_TLS_REJECT_UNAUTHORIZED="0" npm run test-client-cosmos -- -- --reporter mocha-multi-reporters --reporter-options spec=-,mocha-junit-reporter=- $(AdditionalTestArguments)
  #       failOnStderr: true
  #       continueOnError: true
  #       displayName: "npm test"
  #       env:
  #         MOCHA_TIMEOUT: 100000
